//! Standalone HTML reports: one file, inline CSS, no JavaScript, no external
//! resources. It opens from an email attachment or a ticket the same way it
//! opens locally, and follows the reader's light or dark preference.

use hostprint_diff::{Change, ChangeKind, Diff, Significance};
use hostprint_model::format::{bytes, duration};
use hostprint_model::{CollectorStatus, Snapshot};
use std::fmt::Write;

const TOP_PROCESSES: usize = 15;
const LOG_LINES: usize = 30;

/// A report on one snapshot, optionally with the diff that led to it.
pub fn report(snapshot: &Snapshot, diff: Option<&Diff>) -> String {
    let heading = match diff {
        Some(d) => format!("{} → {}", d.from.name, d.to.name),
        None => snapshot.name.clone(),
    };
    let mut h = String::new();
    let _ = writeln!(
        h,
        "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <title>Hostprint: {}</title>\n<style>{CSS}</style>\n</head>\n<body>\n<main>",
        esc(&heading)
    );
    let _ = write!(h, "<header><p class=\"brand\">HOSTPRINT</p><h1>{}</h1>", esc(&heading));
    let _ = writeln!(
        h,
        "<p class=\"meta\">{} · {} · captured by {}</p></header>",
        esc(snapshot.hostname().unwrap_or("unknown host")),
        snapshot.captured_at.format("%Y-%m-%d %H:%M:%S UTC"),
        esc(snapshot.capture.user.as_deref().unwrap_or("unknown user"))
    );
    if let Some(d) = diff {
        diff_section(&mut h, d);
    }
    snapshot_sections(&mut h, snapshot);
    let _ = writeln!(
        h,
        "<footer>Generated by Hostprint {} on {}. Changes are evidence from fixed rules, not conclusions about causes.\
         </footer>\n</main>\n</body>\n</html>",
        env!("CARGO_PKG_VERSION"),
        chrono::Utc::now().format("%Y-%m-%d %H:%M UTC")
    );
    h
}

fn diff_section(h: &mut String, d: &Diff) {
    let elapsed = (d.to.captured_at - d.from.captured_at).num_seconds();
    let _ = write!(
        h,
        "<section><h2>What changed</h2><p class=\"meta\"><b>{}</b> {} → <b>{}</b> {} ({} {})</p>",
        esc(&d.from.name),
        d.from.captured_at.format("%Y-%m-%d %H:%M:%S UTC"),
        esc(&d.to.name),
        d.to.captured_at.format("%Y-%m-%d %H:%M:%S UTC"),
        duration(elapsed.unsigned_abs()),
        if elapsed >= 0 { "later" } else { "earlier" }
    );
    h.push_str("<div class=\"cards\">");
    for (sig, n) in [
        (Significance::High, d.summary.high),
        (Significance::Medium, d.summary.medium),
        (Significance::Low, d.summary.low),
        (Significance::Info, d.summary.info),
    ] {
        let _ = write!(h, "<div class=\"card {}\"><span>{n}</span>{}</div>", class(sig), sig.label());
    }
    h.push_str("</div>");
    for note in &d.notes {
        let _ = write!(h, "<p class=\"note\">⚠ {}</p>", esc(note));
    }
    if d.changes.is_empty() {
        h.push_str("<p>No differences found.</p>");
    }
    for sig in [Significance::High, Significance::Medium, Significance::Low, Significance::Info] {
        let group: Vec<&Change> = d.changes.iter().filter(|c| c.significance == sig).collect();
        if group.is_empty() {
            continue;
        }
        let open = if sig == Significance::Info { "" } else { " open" };
        let _ = write!(
            h,
            "<details{open}><summary><span class=\"badge {}\">{}</span> {} {}</summary>",
            class(sig),
            sig.label(),
            group.len(),
            if group.len() == 1 { "change" } else { "changes" }
        );
        h.push_str("<table><thead><tr><th>Category</th><th>Subject</th><th>Field</th><th>Before</th><th>After</th><th>Change</th><th>Rule</th></tr></thead><tbody>");
        for c in group {
            let (before, after) = match c.kind {
                ChangeKind::Added => (String::new(), c.after.clone().unwrap_or_default()),
                ChangeKind::Removed => (c.before.clone().unwrap_or_default(), String::new()),
                ChangeKind::Changed => (c.before.clone().unwrap_or_default(), c.after.clone().unwrap_or_default()),
            };
            let _ = write!(
                h,
                "<tr><td>{}</td><td><b>{}</b></td><td>{}</td><td class=\"v\">{}</td><td class=\"v\"><b>{}</b></td><td>{}</td><td><code>{}</code></td></tr>",
                esc(&title_case(c.category.label())),
                esc(&c.subject),
                esc(c.field.as_deref().unwrap_or("")),
                esc(&before),
                esc(&after),
                esc(c.delta.as_deref().unwrap_or("")),
                esc(&c.rule)
            );
        }
        h.push_str("</tbody></table></details>");
    }
    h.push_str("</section>\n");
}

fn snapshot_sections(h: &mut String, s: &Snapshot) {
    let _ = write!(h, "<section><h2>System: {}</h2>", esc(&s.name));
    if let Some(host) = &s.host {
        h.push_str("<dl>");
        dl(h, "Host", &host.hostname);
        if let Some(os) = &host.os {
            dl(h, "OS", &os.display());
        }
        if let Some(k) = &host.kernel {
            dl(h, "Kernel", &format!("Linux {k} · {}", host.architecture));
        }
        if let Some(up) = host.uptime_seconds {
            dl(h, "Uptime", &duration(up));
        }
        for (label, value) in
            [("Hardware", &host.hardware), ("Container", &host.container), ("Timezone", &host.timezone)]
        {
            if let Some(v) = value {
                dl(h, label, v);
            }
        }
        h.push_str("</dl>");
    }

    if let Some(r) = &s.resources {
        h.push_str("<h3>Resources</h3><dl>");
        let mut cpu = format!("{} cores", r.cpu.logical_cores);
        if let Some(u) = r.cpu.usage_percent {
            let _ = write!(cpu, " · {u:.0}% busy");
        }
        if let Some(l) = r.load {
            let _ = write!(cpu, " · load {:.2} {:.2} {:.2}", l.one, l.five, l.fifteen);
        }
        dl(h, "CPU", &cpu);
        let mem = r.memory.used_bytes as f64 / r.memory.total_bytes.max(1) as f64;
        let _ = write!(
            h,
            "<dt>Memory</dt><dd>{}{} used of {} · {} available</dd>",
            bar(mem),
            bytes(r.memory.used_bytes),
            bytes(r.memory.total_bytes),
            bytes(r.memory.available_bytes)
        );
        if r.swap.total_bytes > 0 {
            let swap = r.swap.used_bytes as f64 / r.swap.total_bytes as f64;
            let _ = write!(
                h,
                "<dt>Swap</dt><dd>{}{} used of {}</dd>",
                bar(swap),
                bytes(r.swap.used_bytes),
                bytes(r.swap.total_bytes)
            );
        }
        h.push_str("</dl>");
        if !r.disks.is_empty() {
            h.push_str("<table><thead><tr><th>Mount</th><th>Used</th><th>Size</th><th>Free</th><th>Filesystem</th><th>Device</th></tr></thead><tbody>");
            for d in &r.disks {
                let usage = match (d.unresponsive, d.usage_ratio()) {
                    (true, _) => "<span class=\"badge high\">not responding</span>".to_string(),
                    (false, Some(ratio)) => format!("{}{:.0}%", bar(ratio), ratio * 100.0),
                    (false, None) => String::new(),
                };
                let ro = if d.read_only { " <span class=\"badge medium\">read-only</span>" } else { "" };
                let _ = write!(
                    h,
                    "<tr><td><b>{}</b>{ro}</td><td>{usage}</td><td>{}</td><td>{}</td><td>{}</td><td class=\"v\">{}</td></tr>",
                    esc(&d.mount_point),
                    d.total_bytes.map(bytes).unwrap_or_default(),
                    d.available_bytes.map(bytes).unwrap_or_default(),
                    esc(&d.filesystem),
                    esc(&d.device)
                );
            }
            h.push_str("</tbody></table>");
        }
    }

    if let Some(docker) = &s.docker {
        let _ = write!(
            h,
            "<h3>Containers <small>{} · Docker {}</small></h3>",
            docker.containers.len(),
            esc(docker.engine_version.as_deref().unwrap_or("?"))
        );
        h.push_str("<table><thead><tr><th>Name</th><th>State</th><th>Health</th><th>Restarts</th><th>Memory</th><th>Image</th><th>Ports</th></tr></thead><tbody>");
        let mut list: Vec<_> = docker.containers.iter().collect();
        list.sort_by_key(|c| (c.state == "running" && c.health.as_deref() != Some("unhealthy"), c.name.clone()));
        for c in list {
            let health = c.health.as_deref().unwrap_or("–");
            let health_class = match health {
                "unhealthy" => "high",
                "starting" => "medium",
                "healthy" => "ok",
                _ => "",
            };
            let state_class = if c.state == "running" { "" } else { "high" };
            let _ = write!(
                h,
                "<tr><td><b>{}</b></td><td><span class=\"badge {state_class}\">{}</span></td><td><span class=\"badge {health_class}\">{}</span></td><td>{}</td><td>{}</td><td class=\"v\">{}</td><td class=\"v\">{}</td></tr>",
                esc(&c.name),
                esc(&c.state),
                esc(health),
                c.restart_count,
                c.memory_bytes.map(bytes).unwrap_or_default(),
                esc(&c.image),
                esc(&c.ports.join(", "))
            );
        }
        h.push_str("</tbody></table>");
    }

    if let Some(services) = &s.services {
        let failed: Vec<_> = services.iter().filter(|s| s.active_state == "failed").collect();
        let running = services.iter().filter(|s| s.sub_state == "running").count();
        let _ = write!(
            h,
            "<h3>Services <small>{} units · {running} running · {} failed</small></h3>",
            services.len(),
            failed.len()
        );
        for svc in &failed {
            let _ = write!(
                h,
                "<p><span class=\"badge high\">failed</span> <b>{}</b> {}</p>",
                esc(&svc.name),
                esc(svc.description.as_deref().unwrap_or(""))
            );
        }
        h.push_str("<details><summary>All units</summary><table><thead><tr><th>Unit</th><th>State</th><th>Restarts</th><th>Description</th></tr></thead><tbody>");
        for svc in services {
            let _ = write!(
                h,
                "<tr><td>{}</td><td>{} ({})</td><td>{}</td><td>{}</td></tr>",
                esc(&svc.name),
                esc(&svc.active_state),
                esc(&svc.sub_state),
                svc.restarts.map(|r| r.to_string()).unwrap_or_default(),
                esc(svc.description.as_deref().unwrap_or(""))
            );
        }
        h.push_str("</tbody></table></details>");
    }

    if let Some(n) = &s.network {
        let _ = write!(h, "<h3>Listening <small>{} sockets</small></h3>", n.listening.len());
        if n.listening.is_empty() {
            h.push_str("<p class=\"meta\">Nothing is listening.</p>");
        } else {
            h.push_str(
                "<table><thead><tr><th>Protocol</th><th>Address</th><th>Port</th><th>Process</th></tr></thead><tbody>",
            );
            for l in &n.listening {
                let _ = write!(
                    h,
                    "<tr><td>{}</td><td class=\"v\">{}</td><td>{}</td><td>{}</td></tr>",
                    esc(&l.protocol),
                    esc(&l.address),
                    l.port,
                    esc(l.process.as_deref().unwrap_or("?"))
                );
            }
            h.push_str("</tbody></table>");
        }
        h.push_str("<dl>");
        dl(h, "DNS", &n.dns.nameservers.join(", "));
        let routes: Vec<String> =
            n.default_gateways.iter().map(|r| format!("{} via {}", r.gateway, r.interface)).collect();
        dl(h, "Default route", &routes.join(", "));
        h.push_str("</dl>");
    }

    if let Some(p) = &s.processes {
        let mut top: Vec<_> = p.list.iter().collect();
        top.sort_by(|a, b| b.memory_bytes.cmp(&a.memory_bytes).then(a.pid.cmp(&b.pid)));
        let _ = write!(h, "<h3>Processes <small>{} · top {TOP_PROCESSES} by memory</small></h3>", p.list.len());
        h.push_str("<table><thead><tr><th>PID</th><th>Name</th><th>User</th><th>Memory</th><th>CPU%</th><th>Command</th></tr></thead><tbody>");
        for proc in top.into_iter().take(TOP_PROCESSES) {
            let _ = write!(
                h,
                "<tr><td>{}</td><td><b>{}</b></td><td>{}</td><td>{}</td><td>{}</td><td class=\"v\">{}</td></tr>",
                proc.pid,
                esc(&proc.name),
                esc(proc.user.as_deref().unwrap_or("?")),
                bytes(proc.memory_bytes),
                proc.cpu_percent.map(|c| format!("{c:.1}")).unwrap_or_default(),
                esc(&clip(proc.cmdline.as_deref().unwrap_or(""), 160))
            );
        }
        h.push_str("</tbody></table>");
    }

    if s.git.is_some() || s.runtimes.is_some() {
        h.push_str("<h3>Application</h3><dl>");
        if let Some(g) = &s.git {
            dl(h, "Repository", &g.root);
            let subject = g.commit_subject.as_deref().unwrap_or("");
            dl(
                h,
                "Commit",
                &format!(
                    "{} @ {} {subject}",
                    g.branch.as_deref().unwrap_or("(detached)"),
                    g.short_commit().unwrap_or("(none)")
                ),
            );
            dl(h, "Working tree", if g.dirty { "uncommitted changes" } else { "clean" });
        }
        if let Some(rt) = &s.runtimes {
            let list: Vec<String> =
                rt.iter().map(|r| format!("{} {}", r.name, r.version.as_deref().unwrap_or("?"))).collect();
            dl(h, "Runtimes", &list.join(" · "));
        }
        h.push_str("</dl>");
    }

    if let Some(env) = &s.environment {
        let redacted = env.variables.iter().filter(|v| v.redacted).count();
        let _ = write!(
            h,
            "<details><summary>Environment: {} variables, {redacted} redacted</summary><table><tbody>",
            env.variables.len()
        );
        for v in &env.variables {
            let value = if v.redacted {
                format!("<span class=\"badge\">{}</span>", esc(&v.value))
            } else {
                esc(&clip(&v.value, 200))
            };
            let _ = write!(
                h,
                "<tr><td><b>{}</b></td><td class=\"v\">{value}</td><td>{}</td></tr>",
                esc(&v.name),
                esc(&v.source)
            );
        }
        h.push_str("</tbody></table></details>");
    }

    if let Some(logs) = &s.logs {
        let _ = write!(h, "<h3>Logs <small>since {}</small></h3>", logs.since.format("%Y-%m-%d %H:%M:%S UTC"));
        let mut sources: Vec<_> = logs.sources.iter().collect();
        sources.sort_by(|a, b| b.errors.cmp(&a.errors).then(a.name.cmp(&b.name)));
        for src in sources {
            let open = if src.errors > 0 { " open" } else { "" };
            let badge = if src.errors > 0 {
                format!("<span class=\"badge high\">{} errors</span>", src.errors)
            } else {
                String::new()
            };
            let _ = write!(
                h,
                "<details{open}><summary><b>{}</b> <small>{} · {} lines · {} warnings</small> {badge}</summary>",
                esc(&src.name),
                esc(&src.kind),
                src.total,
                src.warnings
            );
            for p in &src.top_errors {
                let _ = write!(h, "<p class=\"v\">×{} {}</p>", p.count, esc(&p.example));
            }
            let start = src.lines.len().saturating_sub(LOG_LINES);
            h.push_str("<pre>");
            for line in &src.lines[start..] {
                h.push_str(&esc(line));
                h.push('\n');
            }
            h.push_str("</pre></details>");
        }
    }

    h.push_str("<h3>Collection</h3><table><tbody>");
    for c in &s.capture.collectors {
        let badge = match c.status {
            CollectorStatus::Ok => "<span class=\"badge ok\">ok</span>",
            CollectorStatus::Partial => "<span class=\"badge medium\">partial</span>",
            CollectorStatus::Skipped => "<span class=\"badge\">skipped</span>",
            CollectorStatus::Failed => "<span class=\"badge high\">failed</span>",
        };
        let mut detail: Vec<String> = c.summary.iter().chain(&c.message).cloned().collect();
        detail.extend(c.notes.iter().cloned());
        let _ = write!(h, "<tr><td>{}</td><td>{badge}</td><td>{}</td></tr>", esc(&c.name), esc(&detail.join("; ")));
    }
    h.push_str("</tbody></table></section>\n");
}

fn dl(h: &mut String, label: &str, value: &str) {
    let _ = write!(h, "<dt>{}</dt><dd>{}</dd>", esc(label), esc(value));
}

/// A usage bar; amber from 70%, red from 90%.
fn bar(ratio: f64) -> String {
    let level = if ratio >= 0.9 {
        " crit"
    } else if ratio >= 0.7 {
        " warn"
    } else {
        ""
    };
    format!("<span class=\"bar{level}\"><i style=\"width:{:.0}%\"></i></span>", (ratio * 100.0).clamp(0.0, 100.0))
}

fn class(sig: Significance) -> &'static str {
    match sig {
        Significance::High => "high",
        Significance::Medium => "medium",
        Significance::Low => "low",
        Significance::Info => "info",
    }
}

/// Escapes text for HTML element content and attribute values.
pub fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

fn clip(s: &str, max: usize) -> String {
    crate::style::clip(s, max)
}

fn title_case(label: &str) -> String {
    let lower = label.to_lowercase();
    let mut chars = lower.chars();
    chars.next().map(|c| c.to_uppercase().chain(chars).collect()).unwrap_or_default()
}

const CSS: &str = r#"
:root{--bg:#fff;--fg:#1d2128;--muted:#667085;--line:#e4e7ec;--zebra:#f8f9fb;--high:#c4320a;--medium:#b54708;--low:#1570ef;--info:#667085;--ok:#067647;--chip:#f2f4f7}
@media (prefers-color-scheme:dark){:root{--bg:#0f1115;--fg:#e6e8eb;--muted:#98a2b3;--line:#262a33;--zebra:#151821;--high:#f97066;--medium:#fdb022;--low:#53b1fd;--info:#98a2b3;--ok:#47cd89;--chip:#1d2230}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.5 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
main{max-width:1180px;margin:0 auto;padding:32px 24px 48px}
header{border-bottom:1px solid var(--line);margin-bottom:24px;padding-bottom:16px}
.brand{margin:0;font-size:12px;font-weight:700;letter-spacing:.12em;color:var(--low)}
h1{margin:4px 0;font-size:26px}h2{font-size:20px;margin:32px 0 8px}h3{font-size:16px;margin:28px 0 8px}
small,.meta{color:var(--muted);font-weight:400}
.cards{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}
.card{min-width:110px;padding:10px 14px;border:1px solid var(--line);border-radius:10px;font-size:12px;font-weight:600;letter-spacing:.06em}
.card span{display:block;font-size:26px;letter-spacing:0}
.card.high span{color:var(--high)}.card.medium span{color:var(--medium)}.card.low span{color:var(--low)}.card.info span{color:var(--info)}
.note{border-left:3px solid var(--medium);padding:6px 12px;background:var(--zebra);margin:8px 0}
details{margin:10px 0}summary{cursor:pointer;padding:6px 0;font-weight:600}
table{width:100%;border-collapse:collapse;margin:8px 0 4px;font-size:14px}
th{text-align:left;color:var(--muted);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.04em;border-bottom:1px solid var(--line);padding:6px 8px}
td{border-bottom:1px solid var(--line);padding:6px 8px;vertical-align:top}
tbody tr:nth-child(even){background:var(--zebra)}
td.v,.v,code,pre{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:13px;word-break:break-all}
pre{background:var(--zebra);border:1px solid var(--line);border-radius:8px;padding:10px 12px;overflow-x:auto;white-space:pre-wrap}
.badge{display:inline-block;padding:1px 8px;border-radius:999px;font-size:12px;font-weight:600;background:var(--chip);color:var(--muted)}
.badge.high{color:var(--high)}.badge.medium{color:var(--medium)}.badge.low{color:var(--low)}.badge.ok{color:var(--ok)}
dl{display:grid;grid-template-columns:max-content 1fr;gap:4px 18px;margin:8px 0}dt{color:var(--muted)}dd{margin:0}
.bar{display:inline-block;width:90px;height:8px;border-radius:4px;background:var(--chip);margin-right:8px;vertical-align:middle;overflow:hidden}
.bar i{display:block;height:100%;background:var(--ok)}.bar.warn i{background:var(--medium)}.bar.crit i{background:var(--high)}
footer{margin-top:40px;padding-top:16px;border-top:1px solid var(--line);color:var(--muted);font-size:13px}
@media (max-width:700px){main{padding:20px 14px}table{display:block;overflow-x:auto}}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn escapes_everything_untrusted() {
        assert_eq!(
            esc("<script>alert('x')</script> & \"y\""),
            "&lt;script&gt;alert(&#39;x&#39;)&lt;/script&gt; &amp; &quot;y&quot;"
        );
    }

    #[test]
    fn bars_change_colour_with_usage() {
        assert!(bar(0.5).starts_with("<span class=\"bar\">"));
        assert!(bar(0.75).contains("bar warn"));
        assert!(bar(0.95).contains("bar crit"));
        assert!(bar(1.7).contains("width:100%"));
    }
}
